services:
  dev-community-ws:
    image: ${DOCKER_REG_ORG:-ljh09060}/${DOCKER_IMG_NAME:-community-ws}:${DOCKER_IMG_TAG:-latest}
    environment:
      - PORT=${CONTAINER_PORT:-3000}
    ports:
      - "${HOST_PORT:-3000}:${CONTAINER_PORT:-3000}"
